name: "🚀 release"

on:
  release:
    types: [published]

jobs:
  release:
    name: 🚀 release
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2
      - name: 🟢 node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: git config --global user.name "muhammadrafeh"
      - run: git config --global user.email "muhammadrafehatique@gmail.com"
      - run: npm version ${{ github.event.release.tag_name }}
      - name: 🚀 publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
